config/routes.rb
Rails.application.routes.draw do
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :admin do
    resources :genres, only: [:index, :edit, :update, :create]

    resources :items, only: [:new, :index, :show, :edit, :create, :update]

    resources :orders, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :customers, only: [:index, :show, :edit, :update]
  end


  namespace :public do
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]


    resources :items, only: [:index, :show]

    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only: [:new, :index, :show, :create]


    resources :deliveries, only: [:index, :edit, :update, :create, :destroy]

    get 'customers/confirm'
    # patch 'customers/withdraw' => 'customers#withdraw' , as: 'withdraw'
    resources :customers, only: [:show, :edit, :update] do
      collection do
      patch :withdraw
      end
    end



  end
    root to: 'homes#top'
    get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!, except: [:top,:about,]
  
    def index
    @customers = Customer.all.page(params[:page]).per(10)
    @customer = current_customer
    end

  def show
    @customer = Customer.find(params[:id])
    
  end
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      if @customer.is_deleted == true
        @customer.update(is_deleted: false)
      else
        @customer.update(is_deleted: true)        
      end
      redirect_to admin_customer_path(@customer), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def edit
       @customer = Customer.find(params[:id])
  end
  
  private
  
  def customer_params
    params.require(:customer).permit( :email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number)
  end

  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1">
    <h2 class = "title-name"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集</h2>
      
      <%= form_with model:@customer,url:admin_customer_path, local:true do |f| %>
      <div class="row">
        <div class = "col-3">
          <div class = "form-group">
            <%= f.label :"　　会員ID" %>
          </div>
        </div>
        <div class = "col-3">
          <div class = "form-group">
            <p>　　　<%= @customer.id %></p>
          </div>  
        </div>
      </div>
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"氏名" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class:"form-control" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name", class:"form-control" %>
          </div>
        </div>
      </div>
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"フリガナ" %>
          </div>
        </div>
        <div class ="col-3">                 
          <div class="form-group">
            <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana", class:"form-control" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class:"form-control" %>
          </div>
        </div>
      </div>
      
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"郵便番号" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class:"form-control" %>
          </div>
        </div>
      </div>
      
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"住所" %>
          </div>
        </div>
        <div class = "col-8">
          <div class="form-group">
            <%= f.text_field :address, autofocus: true, autocomplete: "address", class:"form-control" %>
          </div>
        </div>
      </div>
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"電話番号" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number", class:"form-control" %>
          </div>
        </div>
      </div>
      
      <div class = "row">
    　　<div class = "col-3">
          <div class="form-group">
            <%= f.label :"メールアドレス" %>
          </div>
        </div>
        <div class = "col-3">
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control" %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label :"　　会員ステータス" %>
        <div class = "customer-radio" style = "display:inline">
          　　　　　<%= f.radio_button :is_deleted, :false %><span>有効</span>
          <%= f.radio_button :is_deleted, :true %><span>退会</span>
        </div>
      </div>
      <div class="customer-success">
        <%= f.submit "編集を保存", class: 'btn btn-success' %>
      </div>
    <% end %>
    </div>
  </div>
</div>
  
     

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class="row">
    <div class='col-md-8 offset-md-1'>
    <h2 class= "title-name">会員一覧</h2>
      <table class='table'>
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>

          </tr>
        </thead>
        <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id), class: "black" do %>
              <%= customer.last_name %> <%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
           <% if customer.is_deleted == true %>
            <td class = "gray">無効</td>
           <% else %>
             <td class = "green">有効</td>
             <% end %>
           <% end %>
        </tbody>
      </table>
             <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1">
    <h2 class = "title-name"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</h2>
    <table class= "table none">
        <tbody class="none">
          <tr class="none">
              <th class = "none">会員ID</th>
              <th class = "none"><%= @customer.id %></th>
          </tr>
          <tr class="none">
              <th class = "none">氏名</th>
              <th class = "none"><%= @customer.last_name %> <%= @customer.first_name %></th>
          </tr>
          <tr class="none">
              <th class = "none">フリガナ</th>
              <th class = "none"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></th>
          </tr>
          <tr class="none">
             <th class = "none">郵便番号</th>
             <th class = "none"> <%= @customer.postal_code %></th>
          </tr>
          <tr class="none">
              <th class = "none">住所</th>
              <th class = "none"><%= @customer.address %></th>
          </tr>
         <tr class="none">
              <th class = "none">電話番号</th>
              <th class = "none"><%= @customer.phone_number %></th>
          </tr>
          <tr class="none">
              <th class = "none">メールアドレス</th>
              <th class = "none"><%= @customer.email %></th>
          </tr>
          <tr class="none">
              <th class = "none">ステータス</th>
                <% if @customer.is_deleted == true %>
                    <th class = "none red">無効</th>
                <% else %>
                    <th class = "none green">有効</th>
                <% end %>
          </tr>
        </tbody>
    </table>
      <div class='customer-show'>
         <span> <%= link_to edit_admin_customer_path(@customer),class: "customer-show-edit btn btn-success edit_public_customer_#{@customer.id}" do %> 編集する<% end %></span>
         <span> <%= link_to admin_orders_path(),class: "btn btn-primary edit_public_customer_#{@customer.id}" do %>  注文履歴一覧画面に戻る<% end %></span>
    </div>
    </div>
  </div>
</div>