config/routes.rb
Rails.application.routes.draw do
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :admin do
    resources :genres, only: [:index, :edit, :update, :create]

    resources :items, only: [:new, :index, :show, :edit, :create, :update]

    resources :orders, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :customers, only: [:index, :show, :edit, :update]
  end


  namespace :public do
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]


    resources :items, only: [:index, :show]

    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only: [:new, :index, :show, :create]


    resources :deliveries, only: [:index, :edit, :update, :create, :destroy]

    get 'customers/confirm'
    # patch 'customers/withdraw' => 'customers#withdraw' , as: 'withdraw'
    resources :customers, only: [:show, :edit, :update] do
      collection do
      patch :withdraw
      end
    end



  end
    root to: 'homes#top'
    get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :name, presence: true
  validates :address, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, cooking: 2, preparing: 3, shipped: 4 }

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!, except: [:top,:about]

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "paid_up"

      @order.order_details.each do |o|
        o.update(making_status: "waiting_making")
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status, :making_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<h2>注文履歴一覧</h2>
<% if @orders.each.count == 0 %>
<p>注文はありません</p>
<% else %>

<table class="table">
   <thead>
     <tr>
       <th>購入日時</th>
       <th>購入者</th>
       <th>注文個数</th>
       <th>注文ステータス</th>
     </tr>
   </thead>
   <tbody>
    <% @orders.each do |o| %>
      <tr>
        <td><%= link_to admin_order_path(o), class: "black" do %>
              <%= o.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            <% end %>
        </td>
        <td><%= link_to admin_customer_path(o.customer_id), class: "black"  do %>
              <%= o.customer.last_name + o.customer.first_name %>
            <% end %>
        </td>
        <td><%= o.order_details.sum(:amount) %></td>
        <td><%= o.status_i18n %></td>
      </tr>
    <% end %>
   </tbody>
</table>
<%= paginate @orders %>

<% end %>

app/views/admin/orders/show.html.erb
<div class = "container">
  <h2>　　　注文履歴詳細</h2>
  <div class = "row">
    <div class = "col-sm-1"></div>
    <div class = "col-sm-6">
      <table class = "none">
        <tr class = "none">
          <th class = "none">購入者</th>
          <td class = "none"><%= @order.customer.last_name + @order.customer.first_name %></td>
        </tr>
        <tr class = "none">
          <th class = "none">注文日</th>
          <td class = "none"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr class = "none">
          <th class = "none">配送先</th>
          <td class = "none"><%= @order.full_address %></td>
        </tr>
        <tr class = "none">
          <th class = "none">支払方法</th>
          <td class = "none"><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th class = "none">注文ステータス　</th>

            <td class = "none">
              <%= form_with model: @order, url: admin_order_path(@order), method: :patch do |f| %>
              <%= f.select :status, Order.statuses_i18n.invert %>
                <%= f.submit "更新", class: "btn btn-sm btn-success" %>
              <% end %>
           </td>
        </tr>
      </table>
    </div>
  </div>
  <div class = "row order-table">
    <div class = "col-sm-1"></div>
    <div class = "col-sm-8">
      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |o| %>
            <tr>
              <td><%= o.item.name %></td>
              <td><%= o.price %></td>
              <td><%= o.amount %></td>
              <td><%= o.subtotal %></td>
              <td><%= form_with model: o, url: admin_order_detail_path(o), method: :patch do |f| %>
                    <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                    <%= f.submit "更新", class: "btn btn-sm btn-success" %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class = "col-sm-3 order-show">
      <table class = "none">
        <tr class = "none">
          <th class = "none">商品合計</th>
          <td class = "none"><%= @order.order_details.sum(&:subtotal) %>円</td>
        </tr>
        <tr class = "none">
          <th class = "none">送料</th>
          <td class = "none"><%= @order.shipping_cost %>円</td>
        </tr>
        <tr class = "none">
          <th class = "none">請求金額合計</th>
          <td class = "none"><%= @order.order_details.sum(&:subtotal) + 800 %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>