config/routes.rb
Rails.application.routes.draw do
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  namespace :admin do
    resources :genres, only: [:index, :edit, :update, :create]

    resources :items, only: [:new, :index, :show, :edit, :create, :update]

    resources :orders, only: [:index, :show, :update]

    resources :order_details, only: [:update]

    resources :customers, only: [:index, :show, :edit, :update]
  end


  namespace :public do
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]


    resources :items, only: [:index, :show]

    post 'orders/confirm'
    get 'orders/complete'
    resources :orders, only: [:new, :index, :show, :create]


    resources :deliveries, only: [:index, :edit, :update, :create, :destroy]

    get 'customers/confirm'
    # patch 'customers/withdraw' => 'customers#withdraw' , as: 'withdraw'
    resources :customers, only: [:show, :edit, :update] do
      collection do
      patch :withdraw
      end
    end



  end
    root to: 'homes#top'
    get 'homes/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount.to_i
  end
  

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true


end

app/models/delivery.rb
class Delivery < ApplicationRecord
  
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    validates :genre, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :item_image

    has_many :cart_items, dependent: :destroy
    has_many :order_details, dependent: :destroy
    belongs_to :genre
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    validates :is_active, inclusion: {in: [true, false]}
    validates :genre, presence: true

    def get_item_image(width, height)
        unless item_image.attached?
            file_path = Rails.root.join('app/assets/images/no-image.jpg')
            item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
            item_image.variant(resize_to_limit: [width, height]).processed
    end
    

    def with_tax_price
        (price * 1.1).floor
    end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :name, presence: true
  validates :address, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, paid_up: 1, cooking: 2, preparing: 3, shipped: 4 }

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def subtotal
    price * amount
  end

  enum making_status: { impossible_making: 0, waiting_making: 1, making: 2, finish_making: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!, except: [:top,:about]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    @genres = Genre.new(genres_params)
    @genres.save
    redirect_to admin_genres_path
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genres_params)
    redirect_to admin_genres_path
  end
  
  private
  def genres_params
    params.require(:genre).permit(:genre)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!, except: [:top,:about]

  def index
    @items = Item.all.page(params[:page]).per(10)
    
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(admin_item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end
  
  def create
    @item = Item.new(admin_item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end
  
  
  private
  def admin_item_params
    params.require(:item).permit(:genre_id, :name, :item_image, :introduction, :price, :is_active)
  end
  
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    before_action :authenticate_admin!, except: [:top,:about]

  def index
    @orders = Order.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.status == "paid_up"

      @order.order_details.each do |o|
        o.update(making_status: "waiting_making")
      end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:status, :making_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?


    private

      def after_sign_out_path_for(resource)
        root_path
      end

      protected
    
      def configure_permitted_parameters
         devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number] )
      end

      # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
     
      
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
     @items = Item.all.page(params[:page]).per(4)
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/jenres_helper.rb
module Admin::JenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-blue bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>naganoCAKE</span></a>
        <div>
          <p class="text-white">
          <% if customer_signed_in? %>
          ようこそ<%= current_customer.last_name %>さん
         <% end %>
         </p>
        </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          
      
        <% if customer_signed_in? %>
        <li>
            <%=  link_to public_items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
        </li>
          <li>
            <%= link_to public_customer_path(current_customer),class: 'nav-link text-light' do %>
              マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to public_cart_items_path ,class: 'nav-link text-light' do %>
              カート
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
               ログアウト
            <% end %>
          </li>
        <% elsif admin_signed_in? %>
          <li>
            <%=  link_to admin_items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
          </li>
            <li>
            <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
              会員一覧
            <% end %>
          </li>
           <li>
            <%=  link_to admin_orders_path,class: 'nav-link text-light' do %>
              注文履歴一覧
            <% end %>
          </li>
           <li>
            <%=  link_to admin_genres_path,class: 'nav-link text-light' do %>
              ジャンル一覧
            <% end %>
          </li>
           <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
            ログアウト
            <% end %>
           </li>
            <% else %>
            <li>
              <%= link_to homes_about_path,class: 'nav-link text-light' do %>
              about
            <% end %>
          </li>
           <li>
            <%=  link_to public_items_path,class: 'nav-link text-light' do %>
              商品一覧
            <% end %>
            </li>
            <li>
            <%= link_to new_customer_registration_path ,class: 'nav-link text-light' do %>
              新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path,class: 'nav-link text-light' do %>
               ログイン
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <footer></footer>
  </body>
</html>